#+TITLE: 佛教中的数字
#+AUTHOR: Micky Ching
#+OPTIONS: H:4 ^:nil
#+LATEX_CLASS: latex-doc
#+PAGE_TAGS: buddhism

* 基本算数单位
** 阿僧祇
#+HTML: <!--abstract-begin-->

#+BEGIN_QUOTE
尔时，心王菩萨白佛言：“世尊！诸佛如来演说阿僧祇、无量、无边、无等、不可数、不可
称、不可思、不可量、不可说、不可说不可说。世尊！云何阿僧祇乃至不可说不可说耶？”
佛告心王菩萨言：“善哉善哉！善男子！汝今为欲令诸世间入佛所知数量之义，而问如来、
应、正等觉。善男子！谛听谛听！善思念之！当为汝说。”时，心王菩萨唯然受教。佛言：
“善男子！一百洛叉为一俱胝，俱胝俱胝为一阿庾多，阿庾多阿庾多为一那由他，...，阿
僧祇阿僧祇为一阿僧祇转，阿僧祇转阿僧祇转为一无量，...，不可说不可说为一不可说转，
不可说转不可说转为一不可说不可说，此又不可说不可说为一不可说不可说转。”

------华严经
#+END_QUOTE
#+HTML: <!--abstract-end-->


- 百洛叉   :: $10^5$
- 俱胝     :: $10^{10}$
- 阿庾多   :: $10^{20}$
- 那由他   :: $10^{40}$
- 频波罗   :: $10^{10\times2^3}$
- 矜羯罗   :: $10^{10\times2^4}$
- 阿伽罗   :: $10^{10\times2^5}$
- 最胜     :: $10^{10\times2^6}$
- 阿僧祇   :: $10^{10\times2^{103}}$
- 无量     :: $10^{10\times2^{105}}$
- 无边     :: $10^{10\times2^{107}}$
- 不可思议 :: $10^{10\times2^{115}}$
- 不可量   :: $10^{10\times2^{117}}$
- 不可说   :: $10^{10\times2^{119}}$

** 佛刹微尘数
#+BEGIN_QUOTE
尔时世尊。从两足轮下。放百亿光明。照此三千大千世界。百亿阎浮提。百亿弗婆提。百亿瞿耶尼。百亿郁单越。

------华严经
#+END_QUOTE

具体佛刹微尘数有多大，我没有查找到直接数据，那么可以尝试用下面的方法来计算。

一佛刹即三千大千世界，所谓百亿阎浮提等等表示三千大千世界包括百亿太阳系，
相当于银河系大小，一个佛刹对应一座星系是比较准确的概念。
银河系直径约为 $10^{5}$ 光年，一光年的大小为 $9,460,730,472,580,800$ 米，
总直径约为 $10^{21}$ 米。

假定人的肉眼所见最小颗粒为一个微尘，微尘的直径为 $10^{-4}$ 米。
如果假定不可分割粒子为一个微尘，那么由于现在科学还不能准确限定这个尺寸，
所以不方便引用，但可以肯定的是远远小于肉眼所能分辨的微尘。

因此可以根据以上假定算出佛刹微尘数约为 $10^{75}$ ，
这个概念想对于阿僧祇其实可以忽略不计了。

* 空间计数方法
** 华藏世界海
#+BEGIN_QUOTE
诸佛子！此不可说佛刹微尘数香水海，在华藏庄严世界海中，如天帝网分布而住。

------华严经
#+END_QUOTE
- 华藏世界海 :: 不可说佛刹微尘数香水海

#+BEGIN_QUOTE
此最中央香水海，名：无边妙华光，以现一切菩萨形摩尼王幢为底；出大莲华，名：一切
香摩尼王庄严；有世界种而住其上，名：普照十方炽然宝光明，以一切庄严具为体，有不
可说佛刹微尘数世界于中布列。

------华严经
#+END_QUOTE
- 香水海 :: 不可说佛刹微尘数世界

很显然华藏世界海包括不可说不可说微尘数世界，实际空间范围应该更加广大，
因为世界种仅位于莲花之上，香水海中除了莲花应该还有广阔空间，除此之外，
华藏世界还还包括下面的风轮等。

* 时间计数方法
** 劫
#+BEGIN_QUOTE
如《经》说：“有一比丘问佛言：‘世尊！几许名劫？’佛告比丘：‘我虽能说，汝不能知，
当以譬喻可解：有方百由旬城，溢满芥子，有长寿人过百岁，持一芥子去，芥子都尽，劫
犹不澌。’”“又如方百由旬石，有人百岁，持迦尸轻软叠衣一来拂之，石尽，劫犹不澌。”

------大智度论
#+END_QUOTE

根据大智度论的这段文字依然很难推断一大劫究竟是多少年月，因此这里简单做一个推断。
假定一由旬为16千米，那么方百由旬其约为 $10^{18}$ 立方米，芥子大小按照立方毫米计算，
约为 $10^{-9}$ 立方米，故总时间估算为 $10^{28}$ 年，也就是说一大劫的长度是大于这个数的。

** 寿量劫数
#+BEGIN_QUOTE
然善男子。我实成佛已来。无量无边百千万亿那由他劫。譬如五百千万亿那由他阿僧只三
千大千世界。假使有人末为微尘。过于东方五百千万亿那由他阿僧只国。乃下一尘。如是
东行尽是微尘。诸善男子。于意云何。是诸世界。可得思惟校计知其数不。弥勒菩萨等俱
白佛言。世尊。是诸世界无量无边非算数所知。亦非心力所及。一切声闻辟支佛。以无漏
智。不能思惟知其限数。我等住阿惟越致地。于是事中亦所不达。世尊。如是诸世界无量
无边。尔时佛告大菩萨众。诸善男子。今当分明宣语汝等。是诸世界。若着微尘及不著者。
尽以为尘一尘一劫。我成佛已来。复过于此百千万亿那由他阿僧只劫。

------妙法莲花经
#+END_QUOTE

按照这个比喻来讲，释迦牟尼佛成佛的时间实在过于久远。
